FROM golang:1.8
ENV GOPATH /go

WORKDIR /go/src/github.com/johnatansantana/


RUN cd /go/src/github.com/johnatansantana/ \
    &&  git clone https://github.com/JohnatanSantana/Go.git 
RUN  go get -d ./Go/Api_NBA/  
    # && go install -v ./ \
RUN  go run Go/Api_NBA/main.go

EXPOSE 3000