FROM golang:1.8
ENV GOPATH /go

WORKDIR /go/src/github.com/johnatansantana/


RUN cd /go/src/github.com/johnatansantana/ \
    &&  git clone https://github.com/JohnatanSantana/Go.git 
RUN  go get -d ./Go/Api_NBA/  
    # && go install -v ./ \
# RUN cd ./Go/Api_NBA/ 
    # && go run /go/src/github.com/johnatansantana/Go/Api_NBA/main.go
WORKDIR /go/src/github.com/johnatansantana/Go/Api_NBA/

EXPOSE 3000