FROM golang:1.8
ENV GOPATH /go

WORKDIR /go/src/github.com/johnatansantana/


RUN cd /go/src/github.com/johnatansantana/ \
    &&  git clone https://github.com/JohnatanSantana/Go.git \
    && go get -d ./Go/Api_NBA/  \
    && echo "passou" \
    # && go install -v ./ \
    && go run Go/Api_NBA/main.go

EXPOSE 3000