version: '3.1'
services:
  restapi:
    build: .
    image: golanguinho
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: "go run main.go"
  
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"    
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: passwd1234
    restart: always  